# Generated by Django 3.0.5 on 2022-06-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_appointment_appointmentdate_and_more'),
        ('Hospital', '0002_auto_20220620_2130'),
    ]

    operations = [
    ]
